version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mindplan-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--bind_ip_all"]

  backend:
    build:
      context: ./backend
    container_name: mindplan-backend
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/mindplan
      - JWT_SECRET=secret
      - FRONTEND_URL=http://localhost:5173
      - VITE_DEV_URL=http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: mindplan-frontend
    environment:
      - VITE_PROXY_TARGET=http://backend:5000
      - VITE_BACKEND_URL=http://localhost:5000
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data: